name: Build raspberry ONLINE

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        overprovision-lvm: 'true'
   
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Emulating Raspberry Pi 4
      id: qemu
      uses: pguyot/arm-runner-action@1be4bc9de8a7ba3c1c4f5bf917c438e8dc97904b
      with:
        base_image: http://openhdfpv.org/wp-content/BaseImages/OpenHD-image-pi-bullseye-milestone--2.1-milestones-2022-05-28_1033.zip
        image_additional_mb: 4000
        copy_repository_path: /opt
        copy_artifact_path: gst-plugins-good
        import_github_env: true
        cpu: cortex-a53
        commands: |
            ls -a
            cd /opt
            apt update
            curl -1sLf 'https://dl.cloudsmith.io/public/openhd/openhd-2-1-alpha/setup.deb.sh' | sudo -E bash
            sudo apt install -y openhd-qt-pi-bullseye 
            sudo bash gst-plugins-good/install_dep.sh
            cd /opt/gst-plugins-good
            
            touch /etc/ld.so.conf.d/qt.conf
            echo "/opt/Qt5.15.4/lib/" >/etc/ld.so.conf.d/qt.conf
            sudo ldconfig
            export PATH="$PATH:/opt/Qt5.15.4/bin/"
            git clone https://github.com/GStreamer/gst-plugins-good
            meson --prefix /tmp/gst-plugins-good/usr build
            ninja -C build
            ninja -C build install
            cd /tmp/gst-plugins-good/usr/lib/arm-linux-gnueabihf/gstreamer-1.0/
            sudo cp libgstqmlgl.so ../
            sudo rm -Rf *
            sudo mv ../libgstqmlgl.so . 
            cd /opt
            fpm -a armhf -s dir -t deb -n gst-plugins-good -v 2.2.0-dev -C /tmp/gst-plugins-good -p gst-plugins-good-2.2.0.deb
            ls -a


    - name: Upload to Github
      uses: 'actions/upload-artifact@v2'
      with:
        name: "gst-plugins-good"
        path: |
          *.deb
          
    - name: Push
      id: push
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: "push"
        format: "deb"
        owner: "openhd"
        repo: "openhd-2-1-alpha"
        distro: "raspbian"
        release: "bullseye"
        republish: "true" # needed ONLY if version is not changing
        file: "*.deb"
          
      #- name: Install
      #  run: |
      #    cd OpenHD/build
      #    sudo cmake --install .
      #- name: Build ninja
      #  run: |
      #    sudo apt -y install ninja-build
      #    cd OpenHD
      #    ./build_cmake.sh
